# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         PDL-EditDistance
version:      0.02
version_from: EditDistance.pd
installdirs:  site
requires:
    PDL:                           2.4.2

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30_01
